version: '3'

services:
  clikr:
    build: .
    container_name: clikr-app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./clikr.db:/app/clikr.db
      - ./logs:/app/logs
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
    environment:
      - TZ=Asia/Tehran
      - EXPIRY_DAYS=90
      - INACTIVE_DAYS=180
      - UNUSED_DAYS=365
      - MIN_CLICKS=1